### PR TITLE
Re-organization with jbuilder

### PR DESCRIPTION
**Pull request by rgrinberg**
This is a proposal to re-organize the library and use jbuilder as the main build
system.

The main change is to replace every `re.xxx` library with a `Re.Xxx` module.
This way, we can keep a 1 to 1 mapping between findlib and opam packages while
relying on module aliases to avoid bloated binaries for those who don't use
these sub libraries.

The only thing that's left is to provide some META compatibility and some
aliases for the old `Re_` modules.

### CODE REVIEW

**Comment by Drup** [comment]
That's not how module aliases work. You don't even pass `-no-alias-dep` ! And that implementation uses lot's of top level package names that you should really not use.
On top of being broken, it breaks compat, and the only reason I can think of for that is because dots are prettier than underscores.

If you want to move to jbuilder, fine, but keep the same structure for a first version at least ?

**Comment by rgrinberg** [comment]
Might be a good time to clarify some things.

> That's not how module aliases work. You don't even pass -no-alias-dep

What do you mean by this? where do I need to pass these flagI can think of for that is because dots are prettier than underscores.s where I'm not passing them now? From what I can tell jbuilder is passing all the flags.

>  And that implementation uses lot's of top level package names that you should really not use.

Could you give some examples? I don't see what kind top level package names I shouldn't use.

> On top of being broken, it breaks compat

I don't see how it's broken, but I believe that compat can be preserved with some extra work.

**Comment by Drup** [comment]
Have you tested that it actually works to put your own `re.ml` like that in a jbuilder library and have it be the toplevel entry name ? Because that seems extremely surprising to me if you don't use `(wrapped false)`. 
Not to mention you screw up links in the documentation with your `Re0`.

This is all just completely unnecessary. The current scheme work *fine*. Yes, we have multiple ocamlfind libraries ... so what ? The very tiny convenience is not worth the breakage, nor the increased complexity with your scheme.

As I said, first convert to jbuilder the normal way, then we can discuss fancy schemes.

**Comment by rgrinberg** [comment]
> Have you tested that it actually works to put your own re.ml like that in a jbuilder library and have it be the toplevel entry name ? Because that seems extremely surprising to me if you don't use (wrapped false).

Of course I tested it and it's a standard use case to hide module from being available as `Lib.Xxx`. See for example how [base](https://github.com/janestreet/base/blob/master/src/base.ml) does it.

> Not to mention you screw up links in the documentation with your Re0

Hmm, I didn't expect the links to be broken. Sure, `Re0` isn't pretty though.

> As I said, first convert to jbuilder the normal way, then we can discuss fancy schemes.

Looks like we might be moving past your initial dismissiveness, that's good :)

One of the disadvantages a normal jbuilder doesn't work as well as I'd like is that it doesn't let us hide the cmi for things like `Re_fmt` and various other private modules. This is unsatisfactory to the point where it might be better to use the module aliasing mechanism as I did to control which modules are easily available to the user. I know that things like `Re__Fmt` is still accessible, nevertheless that still seems like a good trade-off.

>  This is all just completely unnecessary. The current scheme work fine. Yes, we have multiple ocamlfind libraries ... so what ? The very tiny convenience is not worth the breakage, nor the increased complexity with your scheme.

The current scheme works fine for you and nobody else. The explosion of names is counter intuitive to all users who haven't spent years with it.. I'm not saying it's urgent to change this, but it's clearly an advantage of my proposed change. Tbh, I also don't see any extra complexity here, but I guess this can be subjective. I do agree with you that the breakage is extremely inconvenient and is really the only real argument. If we found a way to mitigate it, I can't see any reason not to adopt this.

**Comment by Drup** [comment]
I see. I'm quite surprised that it works at all. Still, this is really not worth breaking compatibility, especially since, afaik, having several toplevel modules in the same library would have the same effect as having one top level module with submodule alliases. Have you tried to just group the ocamlfind libraries, and compare the effect on the size of executables ?

> One of the disadvantages a normal jbuilder doesn't work as well as I'd like is that it doesn't let us hide the cmi for things like Re_fmt and various other private modules.

Then better wait for https://github.com/janestreet/jbuilder/pull/106 :p

**Comment by rgrinberg** [comment]
So how about I do a traditional port to jbuilder (maintaining all the top level modules) and wait until the cmi thing to make a release?

Note that I will still get rid of all of these findlib sub libraries. 

> Have you tried to just group the ocamlfind libraries, and compare the effect on the size of executables ?

You mean merge them into 1 findlib? Yes that's my intention. I will compare the effect on size, but i will be really surprised if it changes anything.

Nevetheless, I still think that the library should move to the "prettier" dots eventually. I'll have to think about how to do it without breaking compat. though.

**Comment by Drup** [comment]
Sure, that's a lot more reasonable. I'm afraid any scheme to have a "pretty" module structure will involve messy intermediary names leaking around.

**Comment by rgrinberg** [comment]
> messy intermediary names leaking around

Do you mean names that would be left for compatibility reasons (`Re_emacs` for example) or things like `Re0`?

**Comment by rgrinberg** [comment]
@Drup I've added the compatibility layer and renamed Re0 to Core.

**Comment by rgrinberg** [comment]
The last commit will create a lot of deprecation noise for people. I can revert it if there are objections.

**Comment by rgrinberg** [comment]
@Drup ping? Will merge soon unless there's objections. There are no real issues with this PR.

**Comment by Drup** [comment]
Sorry! I'm a bit swamped lately. I will try to review before next week, but if I still haven't, just merge.

**Comment by Drup** [comment]
Ok, I have looked at the whole thing. I'm pretty happy.The code is decently organized and I have checked that the deprecation warning works well. I will have to live with the loss of abstraction due to the exposed module until we can hide them again. :)

The only thing that I'm unhappy about is the generated documentation: it's really bad. While `Core` is properly included, the links of the module alias are all wrong and don't work as they should and You regularly get `Re__` popping around. I was hoping we could take that ocasion to finally have hosted HTML document... This is even more unfortunate due to the fact that the .mli file don't completely reflect the organization of the library anymore.

To finish, you should probably add yourself as maintaner! :D

**Comment by rgrinberg** [comment]
> The only thing that I'm unhappy about is the generated documentation: it's really bad. While Core is properly included, the links of the module alias are all wrong and don't work as they should and you regularly get Re__ popping around. I was hoping we could take that occasion to finally have nice hosted HTML documentation... This is even more unfortunate due to the fact that the .mli files don't completely reflect the organization of the library anymore.

I think this will need to wait for odoc to address things. I have the same problem in cohttp for example. (cc @aantron).

I got rid of the DEFAULT alias.

**Comment by Drup** [comment]
Yeah, that's expected. 

You can merge when CI is happy. :)

**Comment by rgrinberg** [comment]
I added us both to the list.

I fear that the CI cannot be appeased :/ It did pass on >= 4.02 as expected when it decided to run.

**Pull request merged**
