### PR TITLE
Enable more warnings; warnings are errors

### PR DESCRIPTION
**Pull request by bfops**
Add some warnings (and fix them), and treat all warnings as errors.

### CODE REVIEW

**Comment by Drup** [comment]
1. Don't use `warn_error +a`, this is not future proof. Use `warn_error +1..49`.
2. While not go all the way ? :) I usually use `warn +a-40-42-44`.

**Comment by Drup** [comment]
Oh, and `warn_error -3` too, for the same reasons.

**Comment by rgrinberg** [comment]
The warning tweaks are welcome as long as you make sure that we don't have sudden breakage on newer versions of the compiler.

**Comment by bfops** [comment]
Okay, the line is now `-w +a-40-42-44-3-50-4-48 -warn-error +1..50`.

I added:

  * 48: Implicit elimination of optional arguments
  * 50: unattached documentation comment (ignored)
  * 4: this pattern-matching is fragile.

I think `4` should be enabled temporarily locally, and each case should be considered. I didn't look closely, but I assume the catchall pattern match makes sense in some places and not others.

Also I broke the build, so I need to fix that.

**Comment by Drup** [comment]
Why did you removed 50 ? It's important to generate good ocamldoc. I think you should keep it as non-fatal.

**Comment by bfops** [comment]
I actually thought 50 was just attacking **all** the "postfix" doc comments, but it looks like it's calling out specific issues. Added it back in.

**Comment by Drup** [comment]
@bfops Nice work! thanks for that. This is good for me. :)

**Pull request merged**
