### PR TITLE
Release 1.5.0

### PR DESCRIPTION
**Pull request by rgrinberg**
cc @Drup @bfops @yminsky

### CODE REVIEW

**Comment by Drup** [comment]
yay!

**Comment by hcarty** [comment]
What/where is the `Match` module mentioned in the changelog?  I don't see it in `lib/re.ml` or elsewhere under `lib/`.

**Comment by rgrinberg** [comment]
@hcarty `Re.Match`

**Comment by hcarty** [comment]
I don't see it in the ML or MLI (no `module Match`)

**Comment by rgrinberg** [comment]
@hcarty good catch, what am I saying...

It's `Group`.

https://github.com/ocaml/ocaml-re/blob/master/lib/re.mli#L72

Will fix.

**Comment by hcarty** [comment]
Thanks for the clarification!

**Pull request merged**
